import json
import matplotlib.pyplot as plt

def plot_metrics():
    # Load the data generated by your simulation
    try:
        with open("trust_history.json", "r") as f:
            trust_history = json.load(f)
        with open("research_metrics.json", "r") as f:
            accuracy_history = json.load(f)
    except FileNotFoundError:
        print("Error: JSON files not found. Make sure to run 'python simulation.py' first!")
        return

    # Setup the figure with two side-by-side plots
    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))
    fig.suptitle("UAV Network Dynamic Reputation Defense", fontsize=16, fontweight='bold')

    # --- PLOT 1: Trust Scores ---
    for uav, scores in trust_history.items():
        # Make the compromised UAV stand out in red
        color = 'red' if 'UAV_3' in uav else None
        linestyle = '--' if 'UAV_3' in uav else '-'
        linewidth = 2.5 if 'UAV_3' in uav else 1.5
        
        # Rounds are simply the index of the score list
        rounds = range(len(scores))
        ax1.plot(rounds, scores, label=uav, color=color, linestyle=linestyle, linewidth=linewidth, marker='o')

    ax1.set_title("UAV Trust Scores over Time")
    ax1.set_xlabel("Federated Learning Round")
    ax1.set_ylabel("Trust Score (0 - 100)")
    ax1.set_ylim(-5, 105)
    ax1.grid(True, linestyle=':', alpha=0.7)
    ax1.legend()

    # --- PLOT 2: Validation Accuracy ---
    for uav, accuracies in accuracy_history.items():
        color = 'red' if 'UAV_3' in uav else None
        linestyle = '--' if 'UAV_3' in uav else '-'
        linewidth = 2.5 if 'UAV_3' in uav else 1.5
        
        # We start at round 1 for accuracy (since round 0 has no accuracy yet)
        rounds = range(1, len(accuracies) + 1)
        ax2.plot(rounds, accuracies, label=uav, color=color, linestyle=linestyle, linewidth=linewidth, marker='s')

    ax2.set_title("UAV Model Verification Accuracy")
    ax2.set_xlabel("Federated Learning Round")
    ax2.set_ylabel("Validation Accuracy (%)")
    ax2.set_ylim(-5, 105)
    ax2.grid(True, linestyle=':', alpha=0.7)
    ax2.legend()

    # Adjust layout and show the plot
    plt.tight_layout()
    plt.show()

if __name__ == "__main__":
    print("Generating Capstone Presentation Graphs...")
    plot_metrics()